#!/usr/bin/env bash
apt-get install software-properties-common
apt-get -y update
apt-get install -y haproxy=2.0.*
echo "frontend firstbalance" | tee -a /etc/haproxy/haproxy.cfg
#service haproxy start
echo "bind *:80" | tee -a /etc/haproxy/haproxy.cfg
#echo "mode http" | tee -a /etc/haproxy/haproxy.cfg
echo "default_backend webservers" | tee -a /etc/haproxy/haproxy.cfg
echo "backend webservers" | tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | tee -a /etc/haproxy/haproxy.cfg
echo "server 278-web-01 34.74.227.185:80 check" | tee -a /etc/haproxy/haproxy.cfg
echo "server 278-web-02 100.24.126.241:80 check" | tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
